on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - run: pip install jinja2-cli pyinstaller
    - run: pyinstaller --onefile jinja2cli/cli.py
    - run: mv ./dist/cli* ./dist/jinja2-cli
    # Optionally verify that it works (provided that it does not need user interaction)
    - run: ./dist/jinja2-cli --version
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
